SITE_VISIT_COLS = [
        'GlobalID',
        'review_status',
        'reviewer_name',
        'other_reviewer',
        'record_reviewers',
        'review_date',
        'review_time',
        'entry_review_date',
        'entry_review_time',
        'review_notes',
        'activity_group_id',
        'location_name',
        'entry_park',
        'entry_other_park',
        'park',
        'location_id',
        'entry_location_id',
        'entry_other_location_id',
        'other_location_name',
        'entry_activity_start_date',
        'entry_activity_start_time',
        'visit_type',
        'activity_start_date',
        'activity_start_time',
        'utc_offset',
        'timezone',
        'entry_field_crew',
        'entry_other_field_crew',
        'field_crew',
        'entry_sampleability',
        'entry_other_sampleability',
        'sampleability',
        'site_visit_notes',
        'paper_url1',
        'paper_url2'
        ,'delete_record'
        ,'photos_y_n'
        ,'survey_complete'
        ,'form_version'
        ,'device_id'
        ,'result_file_name'
        ,'analytical_method_id'
        ,'project_id'
        ,'org_code'
        ,'method_detection_limit'
        ,'ncrn_site_name'
        ,'ncrn_latitude'
        ,'ncrn_longitude'
        ,'old_act_id'
        ,'old_act_group_id'
        ,'CreationDate'
        ,'Creator'
        ,'EditDate'
        ,'Editor'
        ,'skip_req_observations'
        ,'skip_req_observations_reason'
        ,'skip_req_ysi'
        ,'skip_req_ysi_reason'
        ,'skip_req_flowtracker'
        ,'skip_req_flowtracker_reason'
        ,'skip_req_grabsample'
        ,'skip_req_grabsample_reason'
        ,'skip_req_photo'
        ,'skip_req_photo_reason'
    ]

FLAT_COLS = [
    'GlobalID'
    ,'ParentGlobalID'
    ,'lab'
    ,'anc_method'
    ,'ysi_increment'
    ,'ysi_probe'
    ,'discharge_instrument'
    ,'grouping_var'
    ,'Characteristic_Name'
    ,'Result_Text'
    ]
